### ISSUE TITLE
grass recipe for conda-forge

### ISSUE THREAD

**Issue by epifanio** [nilason/grass-conda#2]
Hi,
I see you have quite a good knowledge of both grass (configure/build system) and conda (build environment) - it will be great if we could work on making a conda-forge recipe for GRASS. I do have little experience with the conda-build system I can try to help in testing/debugging reporting logs about builds on both Linux and mac platforms. Would this be of interest to you?

BTW, thank you for this repository, it made my life on mac easier and happier ... reminds me of the great efforts made by kingchaos to provide grass on mac!

**Comment by nilason** [comment]
Hi,

> I see you have quite a good knowledge of both grass (configure/build system) and conda (build environment) - it will be great if we could work on making a conda-forge recipe for GRASS. I do have little experience with the conda-build system I can try to help in testing/debugging reporting logs about builds on both Linux and mac platforms. Would this be of interest to you?

In fact, my knowledge on conda is quite rudimentary – but of course, I'll help out with what I can.
> 
> BTW, thank you for this repository, it made my life on mac easier and happier ... reminds me of the great efforts made by kingchaos to provide grass on mac!

I'm really glad it comes to use! In fact the unpredictable state of GRASS for Mac (since Kyngesburye inactivated himself from GRASS), made me embark on this little project.

**Comment by nilason** [comment]
@epifanio I finally started out with a recipe for conda-forge. It is still WIP and only tested so far on Mac. I’d much appreciate if you could give it a try.
https://github.com/nilason/staged-recipes/tree/add-grass

**Comment by cmbarton** [comment]
Cool!  

I'm copying Eric on this too. Can I try it and not mess up my existing binary apps?

Michael
____________________
C. Michael Barton

**Comment by nilason** [comment]
Below are the steps I use to build this. Note this is only tested on a machine with no previously installed conda, using only a fresh installed Mambaforge.

```sh
# download or fork https://github.com/nilason/staged-recipes/tree/add-grass
# and set GRASS_RECIPES_DIR to that location
GRASS_RECIPES_DIR=/path/to/staged-recipes/recipes/grass
# download platform specific miniforge/mambaforge from
# https://github.com/conda-forge/miniforge and set 
# CONDA_FILE accordingly
CONDA_FILE=Mambaforge-MacOSX-xxxx.sh

# install miniconda/miniforge/mambaforge
bash "${CONDA_FILE}"
# (open new shell and continue with:)
conda config --add channels conda-forge
conda config --set channel_priority strict
conda install conda-build
conda install conda-forge-pinning

# build the recipe
cd ./mambaforge
conda build -c conda-forge "${GRASS_RECIPES_DIR}"

# test installing grass in a new environment
conda create --name grasstest --clone base
conda activate grasstest
conda install -c local grass

```

**Comment by mcflugen** [comment]
@nilason This is is amazing! Thank you for getting this going again! 🎉 

Please let me know if you need any help with this.

**Comment by nilason** [comment]
> @nilason This is is amazing! Thank you for getting this going again! 🎉

I'm glad I can contribute in any way :-)

> Please let me know if you need any help with this.

There are two things that I cannot test right now:
1. wxPython for Apple arm64 platform is broken so I cannot test the GUI, only CLI. Would be good to confirm if GUI works (guess it should on x86_64).
2. Absolutely untested on Linux, the patches are inherited. So this is a big one, for anyone interested to dig in.

Once it works for both Mac and Linux, I plan to make a PR of this recipe to [conda-forge/staged-recipes](https://github.com/conda-forge/staged-recipes).

**Comment by wenzeslaus** [comment]
I tested with a continuumio/miniconda3 Docker image. It stopped at:

```
conda build -c conda-forge "${GRASS_RECIPES_DIR}"
```

which fails with:

```
WARNING: No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.22
...
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
...
│  ├─ numpy [1.22.3|1.22.4] would require
│  │  └─ python_abi 3.9 *_pypy39_pp73, which can be installed;
│  └─ numpy 1.22.3 conflicts with any installable versions previously reported;
└─ python 3.11.*  is not installable because it conflicts with any installable versions previously reported.
...
```

I added NumPy version to staged-recipes/recipes/grass/meta.yaml but it was not taken into account. The complain is about conda_build_config.yaml but I don't know where to find that file (the container has many files of this name).

Something special about the `cd ./mambaforge` step? I just replaced that with `mkdir test; cd test`.

A pure Ubuntu image like this:

```
docker ubuntu
apt update
apt install wget git nano
wget https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-x86_64.sh
git clone https://github.com/nilason/staged-recipes/ --branch add-grass
GRASS_RECIPES_DIR=/staged-recipes/recipes/grass/
CONDA_FILE=Miniforge3-Linux-x86_64.sh
bash "${CONDA_FILE}"
bash
conda config --add channels conda-forge
conda config --set channel_priority strict
conda install conda-build conda-forge-pinning
mkdir ./mambaforge
cd ./mambaforge
conda build -c conda-forge "${GRASS_RECIPES_DIR}"
```

also ends with an error, but a different one:

```
...
    Traceback (most recent call last):
      File "/root/miniforge3/lib/python3.10/site-packages/conda/exceptions.py", line 1132, in __call__
        return func(*args, **kwargs)
      File "/root/miniforge3/lib/python3.10/site-packages/conda/cli/main.py", line 69, in main_subshell
        exit_code = do_call(args, p)
      File "/root/miniforge3/lib/python3.10/site-packages/conda/cli/conda_argparse.py", line 115, in do_call
        return args.plugin_subcommand.action(sys.argv[2:])
      File "/root/miniforge3/lib/python3.10/site-packages/conda_build/plugin.py", line 10, in build
        execute(*args, **kwargs)
      File "/root/miniforge3/lib/python3.10/site-packages/conda_build/cli/main_build.py", line 520, in execute
        _parser, args = parse_args(args)
      File "/root/miniforge3/lib/python3.10/site-packages/conda_build/cli/main_build.py", line 474, in parse_args
        check_recipe(args.recipe)
    AttributeError: 'Namespace' object has no attribute 'recipe'
...
```

I tried updating https://github.com/nilason/staged-recipes/tree/add-grass from upstream main, but it didn't make any difference (the update seemed to go well).

Any thoughts?

**Comment by nilason** [comment]
@wenzeslaus It was quite a while since I worked on this, I’ll need to refresh my memory on this and try again.

**Comment by nilason** [comment]
Re: the docker image, I can't tell much on that one.
With the ubuntu image, you hit a `AttributeError: 'Namespace' object has no attribute 'recipe'` error, which I could reproduce and only hardly workaround. Now, it seems to me be caused by a bug in conda (at least up till) version 23.3.1. I can't update conda (`conda update -n base conda`) due to missing support for my machine, but a small patch to `/root/miniforge3/lib/python3.10/site-packages/conda/cli/conda_argparse.py` (taken from changes to that file in https://github.com/conda/conda/commit/330fa91282d9b5e3cc07be795f0aaad23b4f5882) did the work. That change is present with conda 23.5.0.

> Something special about the cd ./mambaforge step? I just replaced that with mkdir test; cd test.

You can skip that part (mkdir and cd), not needed.

I rebased and updated the recipe, so that shouldn't be a big problem. It will for sure need more work, but now it builds GRASS 8.3.1 on Mac at least.

**Comment by cmbarton** [comment]
> Below are the steps I use to build this. Note this is only tested on a machine with no previously installed conda, using only a fresh installed Mambaforge.
> 
> ```shell
> # download or fork https://github.com/nilason/staged-recipes/tree/add-grass
> # and set GRASS_RECIPES_DIR to that location
> GRASS_RECIPES_DIR=/path/to/staged-recipes/recipes/grass
> # download platform specific miniforge/mambaforge from
> # https://github.com/conda-forge/miniforge and set 
> # CONDA_FILE accordingly
> CONDA_FILE=Mambaforge-MacOSX-xxxx.sh
> 
> # install miniconda/miniforge/mambaforge
> bash "${CONDA_FILE}"
> # (open new shell and continue with:)
> conda config --add channels conda-forge
> conda config --set channel_priority strict
> conda install conda-build
> conda install conda-forge-pinning
> 
> # build the recipe
> # cd ./mambaforge   <- not necessary
> conda build -c conda-forge "${GRASS_RECIPES_DIR}"
> 
> # test installing grass in a new environment
> conda create --name grasstest --clone base
> conda activate grasstest
> conda install -c local grass
> ```

Are these still the correct instructions to testing the WIP GRASS conda build? Are there different (or any) instructions for windows?

**Comment by cmbarton** [comment]
I just tried this out on an M2 MacBook running Mac OS 14.5. It got partway through before it failed with the following error:

```
(base) cmbarton@OKED3863 miniforge3 % conda build -c conda-forge "${GRASS_RECIPES_DIR}"
WARNING: No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.23
Adding in variants from internal_defaults
Attempting to finalize metadata for simplejson
Reloading output folder: ...working... done
Getting pinned dependencies: ...working... done
Reloading output folder: ...working... done
Getting pinned dependencies: ...working... done
Reloading output folder: ...working... done
Getting pinned dependencies: ...working... done
BUILD START: ['simplejson-3.8.2-py311h8a0c2ca_0.tar.bz2']
Reloading output folder: ...working... done
Solving environment (_h_env): ...working... done

## Package Plan ##

  environment location: /Applications/anaconda3/conda-bld/simplejson_1718654966466/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold


The following NEW packages will be INSTALLED:

    bzip2:           1.0.8-h93a5062_5          conda-forge
    ca-certificates: 2024.6.2-hf0a4a13_0       conda-forge
    libexpat:        2.6.2-hebf3989_0          conda-forge
    libffi:          3.4.2-h3422bc3_5          conda-forge
    libsqlite:       3.46.0-hfb93653_0         conda-forge
    libzlib:         1.3.1-hfb2fe0b_1          conda-forge
    ncurses:         6.5-hb89a1cb_0            conda-forge
    openssl:         3.3.1-hfb2fe0b_0          conda-forge
    pip:             24.0-pyhd8ed1ab_0         conda-forge
    python:          3.11.9-h932a869_0_cpython conda-forge
    readline:        8.2-h92ec313_1            conda-forge
    setuptools:      70.0.0-pyhd8ed1ab_0       conda-forge
    tk:              8.6.13-h5083fa2_1         conda-forge
    tzdata:          2024a-h0c530f3_0          conda-forge
    wheel:           0.43.0-pyhd8ed1ab_1       conda-forge
    xz:              5.2.6-h57fd34a_0          conda-forge

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
Reloading output folder: ...working... done
Solving environment (_build_env): ...working... done
Reloading output folder: ...working... done
Solving environment (_test_env): ...working... done

## Package Plan ##

  environment location: /Applications/anaconda3/conda-bld/simplejson_1718654966466/_build_env


The following NEW packages will be INSTALLED:

    ca-certificates:       2024.6.2-hf0a4a13_0       conda-forge
    cctools_osx-arm64:     986-hd11630f_0            conda-forge
    clang:                 18.1.7-default_h095aff0_0 conda-forge
    clang-18:              18.1.7-default_hb63da90_0 conda-forge
    clang_impl_osx-arm64:  18.1.7-had71ce8_16        conda-forge
    clang_osx-arm64:       18.1.7-h54d7cd3_16        conda-forge
    clangxx:               18.1.7-default_h095aff0_0 conda-forge
    compiler-rt:           18.1.7-h28df8ea_0         conda-forge
    compiler-rt_osx-arm64: 18.1.7-h56c4e69_0         conda-forge
    icu:                   73.2-hc8870d7_0           conda-forge
    ld64_osx-arm64:        711-h5e7191b_0            conda-forge
    libclang-cpp18.1:      18.1.7-default_hb63da90_0 conda-forge
    libcxx:                17.0.6-h5f092b4_0         conda-forge
    libiconv:              1.17-h0d3ecfb_2           conda-forge
    libllvm18:             18.1.7-h5090b49_1         conda-forge
    libxml2:               2.12.7-ha661575_1         conda-forge
    libzlib:               1.3.1-hfb2fe0b_1          conda-forge
    llvm-tools:            18.1.7-h5090b49_1         conda-forge
    openssl:               3.3.1-hfb2fe0b_0          conda-forge
    sigtool:               0.1.3-h44b9a77_0          conda-forge
    tapi:                  1100.0.11-he4954df_0      conda-forge
    xz:                    5.2.6-h57fd34a_0          conda-forge
    zstd:                  1.5.6-hb46c0d2_0          conda-forge

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
Source cache directory is: /Applications/anaconda3/conda-bld/src_cache
Downloading source to cache: simplejson-3.8.2_2b3a0c466f.tar.gz
Downloading https://pypi.io/packages/source/s/simplejson/simplejson-3.8.2.tar.gz
Success

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/Applications/anaconda3/lib/python3.11/site-packages/conda/exception_handler.py", line 18, in __call__
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "/Applications/anaconda3/lib/python3.11/site-packages/conda/cli/main.py", line 84, in main_subshell
        exit_code = do_call(args, parser)
                    ^^^^^^^^^^^^^^^^^^^^^
      File "/Applications/anaconda3/lib/python3.11/site-packages/conda/cli/conda_argparse.py", line 176, in do_call
        result = plugin_subcommand.action(getattr(args, "_args", args))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Applications/anaconda3/lib/python3.11/site-packages/conda_build/plugin.py", line 17, in build
        return execute(args)
               ^^^^^^^^^^^^^
      File "/Applications/anaconda3/lib/python3.11/site-packages/conda_build/cli/main_build.py", line 590, in execute
        api.build(
      File "/Applications/anaconda3/lib/python3.11/site-packages/conda_build/api.py", line 250, in build
        return build_tree(
               ^^^^^^^^^^^
      File "/Applications/anaconda3/lib/python3.11/site-packages/conda_build/build.py", line 3638, in build_tree
        packages_from_this = build(
                             ^^^^^^
      File "/Applications/anaconda3/lib/python3.11/site-packages/conda_build/build.py", line 2419, in build
        try_download(m, no_download_source=False, raise_error=True)
      File "/Applications/anaconda3/lib/python3.11/site-packages/conda_build/render.py", line 762, in try_download
        source.provide(metadata)
      File "/Applications/anaconda3/lib/python3.11/site-packages/conda_build/source.py", line 1035, in provide
        unpack(
      File "/Applications/anaconda3/lib/python3.11/site-packages/conda_build/source.py", line 169, in unpack
        src_path, unhashed_fn = download_to_cache(
                                ^^^^^^^^^^^^^^^^^^
      File "/Applications/anaconda3/lib/python3.11/site-packages/conda_build/source.py", line 125, in download_to_cache
        raise RuntimeError(
    RuntimeError: SHA256 mismatch: 'd58439c548433adcda98e695be53e526ba940a4b9c44fb9a05d92cd495cdd47f' != '2b3a0c466fb4a1014ea131c2b8ea7c519f9278eba73d6fcb361b7bdb4fd494e9'

`$ /Applications/anaconda3/bin/conda build -c conda-forge /Users/cmbarton/Dropbox (ASU)/GitHub/staged-recipes`

  environment variables:
                 CIO_TEST=<not set>
    CONDA_ALLOW_SOFTLINKS=false
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/Applications/anaconda3/bin/conda
             CONDA_PREFIX=/Applications/anaconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/Applications/anaconda3/bin/python
               CONDA_ROOT=/Applications/anaconda3
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
               LD_PRELOAD=<not set>
                     PATH=/Applications/anaconda3/bin:/Applications/anaconda3/condabin:/usr/loca
                          l/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr
                          /texbin:/opt/X11/bin:/Library/Apple/usr/bin:/var/run/com.apple.securit
                          y.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.sec
                          urity.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.secur
                          ity.cryptexd/codex.system/bootstrap/usr/appleinternal/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : /Applications/anaconda3
            shell level : 1
       user config file : /Users/cmbarton/.condarc
 populated config files : /Users/cmbarton/.condarc
          conda version : 24.5.0
    conda-build version : 24.5.1
         python version : 3.11.6.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=m2
                          __conda=24.5.0=0
                          __osx=14.5=0
                          __unix=0=0
       base environment : /Applications/anaconda3  (writable)
      conda av data dir : /Applications/anaconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/osx-arm64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/osx-arm64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-arm64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Applications/anaconda3/pkgs
                          /Users/cmbarton/.conda/pkgs
       envs directories : /Applications/anaconda3/envs
                          /Users/cmbarton/.conda/envs
               platform : osx-arm64
             user-agent : conda/24.5.0 requests/2.31.0 CPython/3.11.6 Darwin/23.5.0 OSX/14.5 solver/libmamba conda-libmamba-solver/23.11.1 libmambapy/1.5.3
                UID:GID : 503:505
             netrc file : /Users/cmbarton/.netrc
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
If you suspect this error is being caused by a malfunctioning plugin,
consider using the --no-plugins option to turn off plugins.

```

**Comment by nilason** [comment]
> I just tried this out on an M2 MacBook running Mac OS 14.5. It got partway through before it failed with the following error:
> 


I have now updated the recipe, please download again. I managed to get some similar error message after re-trying a failed attempt (You may try `conda build purge` after failed attempts).

As I don't have `MacOSX11.sdk` in conda standard location, I had to set `CONDA_BUILD_SYSROOT` (see https://docs.conda.io/projects/conda-build/en/stable/resources/compiler-tools.html#macos-sdk and https://docs.conda.io/projects/conda-build/en/stable/resources/variants.html#conda-build-variant-config-files).

**Comment by cmbarton** [comment]
Thanks Nicklaus. I’m traveling but will try this again when I get back.Michael Barton...Sent from my iPadOn Aug 12, 2024, at 8:01 AM, Nicklas Larsson ***@***.***> wrote:﻿

I just tried this out on an M2 MacBook running Mac OS 14.5. It got partway through before it failed with the following error:

I have now updated the recipe, please download again. I managed to get some similar error message after re-trying a failed attempt (You may try conda purge after failed attempts).
As I don't have MacOSX11.sdk in conda standard location, I had to set CONDA_BUILD_SYSROOT (see https://docs.conda.io/projects/conda-build/en/stable/resources/compiler-tools.html#macos-sdk and https://docs.conda.io/projects/conda-build/en/stable/resources/variants.html#conda-build-variant-config-files).

**Comment by cmbarton** [comment]
This is still not building. Here is what I am doing. Am I doing something wrong? I've got mambaforge installed

Add path to sdk to conda_build_config.yaml in staged recipes
```
CONDA_BUILD_SYSROOT:
- /Library/Developer/CommandLineTools/SDKs/MacOSX11.0.sdk
```

Then in terminal: 
```
GRASS_RECIPES_DIR=/Users/cmbarton/staged-recipes/recipes/grass  
CONDA_FILE=/Users/cmbarton/grass_source/Miniforge3-MacOSX-arm64.sh
conda config --add channels conda-forge
conda config --set channel_priority strict
cd /Users/cmbarton/miniforge3 
conda build -c conda-forge "${GRASS_RECIPES_DIR}"
conda create --name grasstest --clone base
conda activate grasstest
conda install -c local grass
```

It doesn't get past the build part. Below is the error report. 

(base) cmbarton@OKED3863 miniforge3 % conda build -c conda-forge "${GRASS_RECIPES_DIR}"# test installing grass in a new environment

ERROR: Glob /Users/cmbarton/staged-recipes/recipes/grass# did not match in root_dir /Users/cmbarton/miniforge3
ERROR: Glob /Users/cmbarton/miniforge3/test did not match in root_dir /Users/cmbarton/miniforge3
ERROR: Glob /Users/cmbarton/miniforge3/installing did not match in root_dir /Users/cmbarton/miniforge3
ERROR: Glob /Users/cmbarton/miniforge3/grass did not match in root_dir /Users/cmbarton/miniforge3
ERROR: Glob /Users/cmbarton/miniforge3/in did not match in root_dir /Users/cmbarton/miniforge3
ERROR: Glob /Users/cmbarton/miniforge3/a did not match in root_dir /Users/cmbarton/miniforge3
ERROR: Glob /Users/cmbarton/miniforge3/new did not match in root_dir /Users/cmbarton/miniforge3
ERROR: Glob /Users/cmbarton/miniforge3/environment did not match in root_dir /Users/cmbarton/miniforge3

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/Applications/anaconda3/lib/python3.11/site-packages/conda/exception_handler.py", line 18, in __call__
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "/Applications/anaconda3/lib/python3.11/site-packages/conda/cli/main.py", line 84, in main_subshell
        exit_code = do_call(args, parser)
                    ^^^^^^^^^^^^^^^^^^^^^
      File "/Applications/anaconda3/lib/python3.11/site-packages/conda/cli/conda_argparse.py", line 176, in do_call
        result = plugin_subcommand.action(getattr(args, "_args", args))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Applications/anaconda3/lib/python3.11/site-packages/conda_build/plugin.py", line 17, in build
        return execute(args)
               ^^^^^^^^^^^^^
      File "/Applications/anaconda3/lib/python3.11/site-packages/conda_build/cli/main_build.py", line 589, in execute
        api.build(
      File "/Applications/anaconda3/lib/python3.11/site-packages/conda_build/api.py", line 205, in build
        raise ValueError(
    ValueError: No valid recipes found for input: ['/Users/cmbarton/staged-recipes/recipes/grass#', 'test', 'installing', 'grass', 'in', 'a', 'new', 'environment']

`$ /Applications/anaconda3/bin/conda build -c conda-forge /Users/cmbarton/staged-recipes/recipes/grass# test installing grass in a new environment`

  environment variables:
                 CIO_TEST=<not set>
    CONDA_ALLOW_SOFTLINKS=false
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/Applications/anaconda3/bin/conda
             CONDA_PREFIX=/Applications/anaconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/Applications/anaconda3/bin/python
               CONDA_ROOT=/Applications/anaconda3
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
               LD_PRELOAD=<not set>
                     PATH=/Applications/anaconda3/bin:/Applications/anaconda3/condabin:/usr/loca
                          l/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr
                          /texbin:/opt/X11/bin:/Library/Apple/usr/bin:/var/run/com.apple.securit
                          y.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.sec
                          urity.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.secur
                          ity.cryptexd/codex.system/bootstrap/usr/appleinternal/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : /Applications/anaconda3
            shell level : 1
       user config file : /Users/cmbarton/.condarc
 populated config files : /Users/cmbarton/.condarc
          conda version : 24.7.1
    conda-build version : 24.7.1
         python version : 3.11.6.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=m2
                          __conda=24.7.1=0
                          __osx=14.5=0
                          __unix=0=0
       base environment : /Applications/anaconda3  (writable)
      conda av data dir : /Applications/anaconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/osx-arm64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/osx-arm64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-arm64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Applications/anaconda3/pkgs
                          /Users/cmbarton/.conda/pkgs
       envs directories : /Applications/anaconda3/envs
                          /Users/cmbarton/.conda/envs
               platform : osx-arm64
             user-agent : conda/24.7.1 requests/2.32.3 CPython/3.11.6 Darwin/23.5.0 OSX/14.5 solver/libmamba conda-libmamba-solver/23.12.0 libmambapy/1.5.4
                UID:GID : 503:505
             netrc file : /Users/cmbarton/.netrc
           offline mode : False

**Comment by nilason** [comment]
I see you have anaconda installed. My procedure assumes a "clean" environment to build with miniforge. But it should of course work with a pre-installed anaconda as well. I'd try from the `conda build -c conda-forge "${GRASS_RECIPES_DIR}"` step (just make sure you remove the ~/miniforge3 dir).

**Comment by cmbarton** [comment]
My first attempt did not work. But it did show me a problem. When I clone your staged-recipes repository, it does not include the grass recipe. However, if I download the zip file I get "staged-recipes-add-grass", which does include the grass recipe. My initial tries with the latter have failed and I'll try a couple more things.

**Comment by cmbarton** [comment]
Now I find that the zip file (staged-recipes-add-grass) is missing conda_build_config.yaml (where I can specify the location of the SDK) but it has much more info in the conda-forge.yml than the cloned repository (staged-recipes), which only lists windows.  I cloned and downloaded the zip from the add-grass branch of the staged-recipes repository. But I am confused as to which set of files to use.

**Comment by nilason** [comment]
There are some possible variations for conda_build_config.yaml, see https://docs.conda.io/projects/conda-build/en/stable/resources/variants.html#conda-build-variant-config-files.

**Comment by nilason** [comment]
> There are some possible variations for conda_build_config.yaml, see https://docs.conda.io/projects/conda-build/en/stable/resources/variants.html#conda-build-variant-config-files.

The 4th point is perhaps the most convenient.

**Comment by cmbarton** [comment]
I'm using a conda_build_config.yaml that looks like this:

```
MACOSX_DEPLOYMENT_TARGET:  # [osx]
  - 11.0                   # [osx]
CONDA_BUILD_SYSROOT:
  - /Library/Developer/CommandLineTools/SDKs/MacOSX11.0.sdk
```

**Comment by cmbarton** [comment]
The conda-forge.yml in the cloned staged-recipes repository looks like this:

```
channel_priority: strict
azure:
  settings_win:
    pool:
      vmImage: windows-2022
```

And the same file in the downloaded zip file repository staged-recipes-add-grass looks like this: 

```
build_platform:
  linux_aarch64: linux_64
  linux_ppc64le: linux_64
  osx_arm64: osx_64
conda_forge_output_validation: true
provider:
  linux: azure
  linux_aarch64: azure
  linux_ppc64le: azure
  osx: azure
  win: azure
test_on_native_only: true
os_version:
  linux_64: cos7

channel_priority: strict
# azure:
#   settings_win:
#     pool:
#       vmImage: windows-2022
```

**Comment by cmbarton** [comment]
Without miniforge, here is what happens. It says that there are no valid recipes, even though the grass folder is indeed inside the recipes folder. I wonder if there is something somewhere that is hard-coded to your environment that we are missing. 

```
(base) cmbarton@OKED3863 ~ % GRASS_RECIPES_DIR=/Users/cmbarton/staged-recipes-add-grass/recipes/grass  
(base) cmbarton@OKED3863 ~ % conda build -c conda-forge "${GRASS_RECIPES_DIR}"# test installing grass in a new environment
```

ERROR: Glob /Users/cmbarton/staged-recipes-add-grass/recipes/grass# did not match in root_dir /Users/cmbarton
ERROR: Glob /Users/cmbarton/test did not match in root_dir /Users/cmbarton
ERROR: Glob /Users/cmbarton/installing did not match in root_dir /Users/cmbarton
ERROR: Glob /Users/cmbarton/grass did not match in root_dir /Users/cmbarton
ERROR: Glob /Users/cmbarton/in did not match in root_dir /Users/cmbarton
ERROR: Glob /Users/cmbarton/a did not match in root_dir /Users/cmbarton
ERROR: Glob /Users/cmbarton/new did not match in root_dir /Users/cmbarton
ERROR: Glob /Users/cmbarton/environment did not match in root_dir /Users/cmbarton

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/Applications/anaconda3/lib/python3.11/site-packages/conda/exception_handler.py", line 18, in __call__
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "/Applications/anaconda3/lib/python3.11/site-packages/conda/cli/main.py", line 84, in main_subshell
        exit_code = do_call(args, parser)
                    ^^^^^^^^^^^^^^^^^^^^^
      File "/Applications/anaconda3/lib/python3.11/site-packages/conda/cli/conda_argparse.py", line 176, in do_call
        result = plugin_subcommand.action(getattr(args, "_args", args))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Applications/anaconda3/lib/python3.11/site-packages/conda_build/plugin.py", line 17, in build
        return execute(args)
               ^^^^^^^^^^^^^
      File "/Applications/anaconda3/lib/python3.11/site-packages/conda_build/cli/main_build.py", line 589, in execute
        api.build(
      File "/Applications/anaconda3/lib/python3.11/site-packages/conda_build/api.py", line 205, in build
        raise ValueError(
    ValueError: No valid recipes found for input: ['/Users/cmbarton/staged-recipes-add-grass/recipes/grass#', 'test', 'installing', 'grass', 'in', 'a', 'new', 'environment']

`$ /Applications/anaconda3/bin/conda build -c conda-forge /Users/cmbarton/staged-recipes-add-grass/recipes/grass# test installing grass in a new environment`

**Comment by nilason** [comment]
> ```
> conda build -c conda-forge "${GRASS_RECIPES_DIR}"# test installing grass in a new environment
> ```

You must delete the “# test installing grass in a new environment” part from the command.

**Comment by cmbarton** [comment]
Thought I clipped that out. Tried again without the comment and have a different error. Could this have to do with the conda-forge.yml file referenced a couple comments above (with build_platform: line "osx_arm64: osx_64")?

```
(base) cmbarton@OKED3863 ~ % GRASS_RECIPES_DIR=/Users/cmbarton/staged-recipes-add-grass/recipes/grass
(base) cmbarton@OKED3863 ~ % conda build -c conda-forge "${GRASS_RECIPES_DIR}"
```

WARNING: No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.23
Adding in variants from internal_defaults
Attempting to finalize metadata for grass
Reloading output folder: ...working... done
Getting pinned dependencies: ...working... failed
WARNING: failed to get package records, retrying.  exception was: Unsatisfiable dependencies for platform osx-arm64: {MatchSpec("c_osx-arm64")}
Encountered problems while solving:
  - nothing provides requested c_osx-arm64

Could not solve for environment specs
The following package could not be installed
└─ c_osx-arm64 does not exist (perhaps a typo or a missing channel).
Reloading output folder: ...working... done
Getting pinned dependencies: ...working... failed
Reloading output folder: ...working... done
Getting pinned dependencies: ...working... failed
Reloading output folder: ...working... done
Getting pinned dependencies: ...working... failed
ERROR: Failed to get package records, max retries exceeded.

Leaving build/test directories:
  Work:
 /Applications/anaconda3/conda-bld/work 
  Test:
 /Applications/anaconda3/conda-bld/test_tmp 
Leaving build/test environments:
  Test:
source activate  /Applications/anaconda3/conda-bld/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold 
  Build:
source activate  /Applications/anaconda3/conda-bld/_build_env 



ExplainedDependencyNeedsBuildingError: Unsatisfiable dependencies for platform osx-arm64: {MatchSpec("c_osx-arm64")}
Encountered problems while solving:
  - nothing provides requested c_osx-arm64

Could not solve for environment specs
The following package could not be installed
└─ c_osx-arm64 does not exist (perhaps a typo or a missing channel).

**Comment by cmbarton** [comment]
in staged-recipes-add-grass/.ci_support/osx64.yaml, targets are set to 10.13 and that won't work with an ARM processor. Unfortunately when I changed them to:

```
c_stdlib_version:
  - 11
MACOSX_DEPLOYMENT_TARGET:
  - 11
```

it still is giving the same └─ c_osx-arm64 does not exist does not exist error. So far, I have not found any reference to this.
